# import_bash_completion.ps1
#
# Parses a bash completion script (generated by clap / cobra / etc.) and
# produces a WinSH external completion definition TOML file.
#
# Supported bash patterns:
#   opts="--flag1 --flag2 ..."           -> top-level flag list
#   case "${prev}" in
#     --flag) compgen -W "a b c" ...     -> static value list
#     --flag) compgen -f  ...            -> path completion
#   esac
#
# Usage:
#   .\import_bash_completion.ps1 -InputScript fd.bash -OutputToml fd.toml
#   .\import_bash_completion.ps1 -InputScript fd.bash   # prints to stdout

param(
    [Parameter(Mandatory=$true)]
    [string]$InputScript,

    [string]$OutputToml,

    # Override the command name (defaults to the basename of the script without leading _)
    [string]$CommandName
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ─── Read source ──────────────────────────────────────────────────────────────
$lines = Get-Content $InputScript

# ─── Determine command name ───────────────────────────────────────────────────
if (-not $CommandName) {
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($InputScript)
    $CommandName = $baseName.TrimStart('_')
}

# ─── Extract all flags from the opts="..." line ───────────────────────────────
# Handles multi-line by joining the whole file first
$content = $lines -join "`n"

$allFlags = @()
if ($content -match 'opts="([^"]+)"') {
    $optsStr = $Matches[1]
    # Split on whitespace, keep only tokens starting with - 
    $allFlags = ($optsStr -split '\s+') | Where-Object { $_ -match '^-' }
}

# ─── Parse case "${prev}" blocks ──────────────────────────────────────────────
# Build a hashtable: flag -> @{ type = 'static'|'path'; values = @() }
# Use case-SENSITIVE dictionary (PowerShell default @{} is case-insensitive,
# which would confuse -S and -s etc.)
$flagValues = [System.Collections.Generic.Dictionary[string,hashtable]]::new(
    [System.StringComparer]::Ordinal
)

$inCase   = $false
$curFlags = @()  # flags being accumulated for the current case arm

foreach ($line in $lines) {
    $trimmed = $line.Trim()

    # Detect entry into the case block
    if ($trimmed -match 'case "\$\{prev\}"') {
        $inCase = $true
        continue
    }

    if (-not $inCase) { continue }

    # End of case block
    if ($trimmed -eq 'esac') {
        $inCase = $false
        $curFlags = @()
        continue
    }

    # Case arm: --flag) or -f)
    if ($trimmed -match '^(-[\w-]+)\)$') {
        $curFlags = @($Matches[1])
        continue
    }

    # Multiple patterns on one line (-t | --type) — rare but handle it
    if ($trimmed -match '^((?:-[\w-]+\|?)+)\)$') {
        $curFlags = ($Matches[1] -split '\|') | ForEach-Object { $_.Trim() }
        continue
    }

    # Wildcard arm *)  — reset
    if ($trimmed -match '^\*\)') {
        $curFlags = @()
        continue
    }

    # compgen -W "a b c ..."  → static values
    if ($curFlags.Count -gt 0 -and $trimmed -match 'compgen\s+-W\s+"([^"]+)"') {
        $vals = ($Matches[1] -split '\s+') | Where-Object { $_ -ne '' }
        foreach ($f in $curFlags) {
            $flagValues[$f] = [hashtable]@{ type = 'static'; values = $vals }
        }
        $curFlags = @()
        continue
    }

    # compgen -f  → path completion
    if ($curFlags.Count -gt 0 -and $trimmed -match 'compgen\s+-f') {
        foreach ($f in $curFlags) {
            $flagValues[$f] = [hashtable]@{ type = 'path'; values = @() }
        }
        $curFlags = @()
        continue
    }

    # return 0 / ;; — end of arm body, reset
    if ($trimmed -match '^(return|;;)') {
        $curFlags = @()
    }
}

# ─── Group flags: merge short+long aliases that share the same values ─────────
# Map each flag to its canonical info; then pair short↔long when they match.
# Strategy: separate flags into --long and -s buckets, then pair by identical values.

$longFlags  = $allFlags | Where-Object { $_ -match '^--' }
$shortFlags = $allFlags | Where-Object { $_ -match '^-[^-]' }

# Flags that appear in flagValues (have value info)
# Build: canonical long -> { short, valInfo }
$paired   = @{}  # long -> @{ short; valInfo }
$usedShort = @{}

foreach ($long in $longFlags) {
    $valInfo = if ($flagValues.ContainsKey($long)) { $flagValues[$long] } else { $null }  # case-sensitive lookup

    # Try to find a matching short flag.
    # ONLY pair when BOTH flags have IDENTICAL static value lists.
    # Do NOT pair path-type flags — they are indistinguishable and pairing them
    # would produce wrong short↔long associations.
    $matchedShort = $null
    if ($null -ne $valInfo -and $valInfo.type -eq 'static') {
        foreach ($short in $shortFlags) {
            if ($usedShort.ContainsKey($short)) { continue }
            $sv = if ($flagValues.ContainsKey($short)) { $flagValues[$short] } else { $null }  # case-sensitive lookup

            if ($null -ne $sv -and $sv.type -eq 'static' -and
                ($valInfo.values -join '|') -eq ($sv.values -join '|')) {
                $matchedShort = $short
                $usedShort[$short] = $true
                break
            }
        }
    }

    $paired[$long] = @{ short = $matchedShort; valInfo = $valInfo }
}

# Short flags that were not paired with any long flag
$unpairedShort = $shortFlags | Where-Object { -not $usedShort.ContainsKey($_) }

# ─── Render TOML ──────────────────────────────────────────────────────────────
function Format-TomlString([string]$s) { '"' + $s.Replace('\','\\').Replace('"','\"') + '"' }

$sb = [System.Text.StringBuilder]::new()

$null = $sb.AppendLine("# Auto-generated by import_bash_completion.ps1")
$null = $sb.AppendLine("# Source: $InputScript")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("command = $(Format-TomlString $CommandName)")
$null = $sb.AppendLine("")

# Long flags (with optional paired short)
foreach ($long in ($paired.Keys | Sort-Object)) {
    $info     = $paired[$long]
    $short    = $info.short
    $valInfo  = $info.valInfo

    $null = $sb.AppendLine("[[flags]]")
    if ($short) {
        $null = $sb.AppendLine("short = $(Format-TomlString $short)")
    }
    $null = $sb.AppendLine("long  = $(Format-TomlString $long)")

    if ($null -ne $valInfo) {
        if ($valInfo.type -eq 'path') {
            $null = $sb.AppendLine("takes_value = true")
            $null = $sb.AppendLine('values_from = "path"')
        } elseif ($valInfo.type -eq 'static' -and $valInfo.values.Count -gt 0) {
            $null = $sb.AppendLine("takes_value = true")
            $vals = ($valInfo.values | ForEach-Object { Format-TomlString $_ }) -join ', '
            $null = $sb.AppendLine("values = [$vals]")
        }
    }
    $null = $sb.AppendLine("")
}

# Short flags that were NOT paired (includes path-type short flags listed individually)
foreach ($short in ($unpairedShort | Sort-Object)) {
    $valInfo = if ($flagValues.ContainsKey($short)) { $flagValues[$short] } else { $null }

    $null = $sb.AppendLine("[[flags]]")
    $null = $sb.AppendLine("short = $(Format-TomlString $short)")

    if ($null -ne $valInfo) {
        if ($valInfo.type -eq 'path') {
            $null = $sb.AppendLine("takes_value = true")
            $null = $sb.AppendLine('values_from = "path"')
        } elseif ($valInfo.type -eq 'static' -and $valInfo.values.Count -gt 0) {
            $null = $sb.AppendLine("takes_value = true")
            $vals = ($valInfo.values | ForEach-Object { Format-TomlString $_ }) -join ', '
            $null = $sb.AppendLine("values = [$vals]")
        }
    }
    $null = $sb.AppendLine("")
}

$toml = $sb.ToString()

# ─── Output ───────────────────────────────────────────────────────────────────
if ($OutputToml) {
    $toml | Set-Content -Encoding UTF8 $OutputToml
    Write-Host "Written to $OutputToml"
} else {
    Write-Output $toml
}
